# Generated by Django 4.1.2 on 2023-05-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_article',
        ),
    ]
