# Generated by Django 4.1.2 on 2023-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_description_article_author_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_article',
            field=models.DateField(blank=True, null=True, verbose_name='Date create article'),
        ),
    ]
